import{a,i as d}from"./assets/vendor-96017409.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const c of n.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function o(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerpolicy&&(n.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?n.credentials="include":e.crossorigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function i(e){if(e.ep)return;e.ep=!0;const n=o(e);fetch(e.href,n)}})();a.defaults.baseURL="https://api.thecatapi.com/v1";a.defaults.headers.common["x-api-key"]="live_sFk9zT8l2vQd7Y8HEpVtQUNkiz5NdWfSDo35O2SJIILl76Dl3HE1XRDHR3aF8Vh0";function m(){return a.get("/breeds").then(t=>t.data)}function h(t){return a.get(`/images/search?breed_ids=${t}`).then(r=>r.data[0])}const l=document.querySelector(".breed-select"),u=document.querySelector(".cat-info"),s=document.querySelector(".loader"),f=document.querySelector(".myBox");l.addEventListener("change",p);f.setAttribute("hidden","hidden");function p(t){u.innerHTML="";const r=t.currentTarget.value;h(r).then(y).catch(o=>d.error({message:"Oops! Something went wrong! Try reloading the page!"})).finally(s.removeAttribute("hidden","hidden"))}m().then(t=>{l.insertAdjacentHTML("afterbegin",g(t))}).catch(t=>d.error({message:"Oops! Something went wrong! Try reloading the page!"}));function g(t){return s.setAttribute("hidden","hidden"),f.removeAttribute("hidden","hidden"),t.map(({id:r,name:o})=>`<option value="${r}">${o}</option>`).join("")}function y(t){t===void 0&&s.setAttribute("hidden","hidden");const{url:r,breeds:o}=t,i=`
    <img class="image" src="${r}" alt="${o[0].name}" />
    <div class="cat-info-text">
      <h2 class="cat-name">${o[0].name}</h2>
      <p class="cat-description">${o[0].description}</p>
      <p><span class="temperament">Temperament:</span> ${o[0].temperament}</p>
    </div>
  `;s.setAttribute("hidden","hidden"),u.innerHTML=i}
//# sourceMappingURL=commonHelpers.js.map
